version: "3"

services:
  wildflyswarm:
    image: evgeniy-khist/geocluster-example
    ports:
      - "8080:8080"
    depends_on:
      - postgresql

  nginx:
    image: nginx:1.11.10
    volumes:
      - ./webapp/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./webapp/html:/usr/share/nginx/sites/geocluster-example:ro
    ports:
      - "8000:80"
    depends_on:
      - wildflyswarm

  postgresql:
    image: postgres:9.6.2
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=changeit
      - POSTGRES_DB=exampledb
    ports:
      - "5432:5432"
